// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RamenStore.Infrastructure;

#nullable disable

namespace RamenStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("RamenStore.Domain.Entities.Broths.Broth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageInactive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Broths");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Description = "Simple like the seawater, nothing more",
                            ImageActive = "https://tech.redventures.com.br/icons/salt/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/salt/inactive.svg",
                            Name = "Salt",
                            Price = 10m
                        },
                        new
                        {
                            Id = "2",
                            Description = "The good old and traditional soy sauce",
                            ImageActive = "https://tech.redventures.com.br/icons/shoyu/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/shoyu/inactive.svg",
                            Name = "Shoyu",
                            Price = 10m
                        },
                        new
                        {
                            Id = "3",
                            Description = "Paste made of fermented soybeans",
                            ImageActive = "https://tech.redventures.com.br/icons/miso/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/miso/inactive.svg",
                            Name = "Miso",
                            Price = 12m
                        });
                });

            modelBuilder.Entity("RamenStore.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrothId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProteinId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RamenStore.Domain.Entities.Proteins.Protein", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageActive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageInactive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Proteins");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Description = "A sliced flavourful pork meat with a selection of season vegetables.",
                            ImageActive = "https://tech.redventures.com.br/icons/pork/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/pork/inactive.svg",
                            Name = "Chasu",
                            Price = 10m
                        },
                        new
                        {
                            Id = "2",
                            Description = "A delicious vegetarian lamen with a selection of season vegetables.",
                            ImageActive = "https://tech.redventures.com.br/icons/yasai/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/yasai/inactive.svg",
                            Name = "Yasai Vegetarian",
                            Price = 10m
                        },
                        new
                        {
                            Id = "3",
                            Description = "Three units of fried chicken, moyashi, ajitama egg and other vegetables.",
                            ImageActive = "https://tech.redventures.com.br/icons/chicken/active.svg",
                            ImageInactive = "https://tech.redventures.com.br/icons/chicken/inactive.svg",
                            Name = "Karaague",
                            Price = 12m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
